version: 'latest'

services:
    db:
        image: postgres
        container_name: postgres_container
        restart: always
        ports:
            - '5432:5432' # PostgreSQL
        volumes:
            - ./data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=mydb # Development DB
            - POSTGRES_USER=myuser
            - POSTGRES_PASSWORD=mypassword
        networks:
            inviteme_network:
                ipv4_address: 172.20.0.2

    nextjs-inviteme:
        image: node
        volumes:
            - ./:/usr/src/app
        container_name: nextjs-inviteme
        restart: always
        ports:
            - '3000:3000'
        environment:
            - DATABASE_URL="postgresql://myuser:mypassword@172.20.0.2:5432/mydb"
        networks:
            inviteme_network:
                ipv4_address: 172.20.0.5
        depends_on:
            - db
        working_dir: /usr/src/app
        command: sh -c "npm install && npm run dev"

networks:
    inviteme_network:
        ipam:
            driver: default
            config:
                - subnet: 172.20.0.0/16