version: 'latest'

services:
    nextjs-inviteme:
        image: node
        container_name: nextjs-container
        working_dir: /usr/src/app
        volumes:
            - .:/usr/src/app
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=development
            - DATABASE_URL=postgresql://myuser:mypassword@postgres-container:5432/mydb?schema=public
        command: sh -c "npm install && npm run dev"

    postgres-db:
        image: postgres:latest
        container_name: postgres-container
        restart: always
        ports:
            - '5432:5432'
        volumes:
            - ./app:/usr/src/app
        environment:
            - POSTGRES_DB=mydb
            - POSTGRES_USER=myuser
            - POSTGRES_PASSWORD=mypassword

networks:
    default:
        driver: bridge
